name: CI - Lint & Docker Build

on:
  pull_request:
    branches: [master]  # Add other branches if needed

jobs:
  lint-and-docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Docker Build
        run: docker build -t foodmate-app .
